build: false

environment:
  matrix:
    - PYTHON: "C:\\Python27"
      PYTHON_VERSION: "2.7.8"
      PYTHON_ARCH: "32"

    - PYTHON: "C:\\Python27"
      PYTHON_VERSION: "2.7.10"
      PYTHON_ARCH: "32"


init:
  - "ECHO ----------------------------------------------------------------------------------------------"
  - "ECHO Initializing on PY_VERSION=%PYTHON_VERSION% PY_ARCHITECTURE=%PYTHON_ARCH% Located at %PYTHON%"
  - "ECHO ----------------------------------------------------------------------------------------------"

install:
  - "%PYTHON%/Scripts/pip.exe install nose"
  - "%PYTHON%/Scripts/pip.exe install coverage"

test_script:
  - "%PYTHON%/Scripts/nosetests"