build: false

environment:
  matrix:
    - PYTHON: "C:\\Python27"
      PYTHON_VERSION: "2.7.8"
      PYTHON_ARCH: "32"

    - PYTHON: "C:\\Python27"
      PYTHON_VERSION: "2.7.10"
      PYTHON_ARCH: "32"


init:
  - "ECHO ----------------------------------------------------------------------------------------------"
  - "ECHO Initializing on PY_VERSION=%PYTHON_VERSION% PY_ARCHITECTURE=%PYTHON_ARCH% Located at %PYTHON%"
  - "ECHO ----------------------------------------------------------------------------------------------"

install:
  - "%PYTHON%/Scripts/pip.exe install nose"
  - "%PYTHON%/Scripts/pip.exe install coverage"

test_script:
  - "%PYTHON%/Scripts/nosetests"

version: 0.1.{build}

notifications:
  # Email
  - provider: Email
    to:
      - adam@signalbase.com
    subject: 'Build {{status}}'                  # optional
    message: "{{message}}, {{commitId}}, ..."    # optional
    on_build_status_changed: true

  - provider: Slack
    incoming_webhook: https://hooks.slack.com/services/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
    template: |
              <{{buildUrl}}|Build {{projectName}} {{buildVersion}} {{status}}>
              Commit <{{commitUrl}}|{{commitId}}> by {{commitAuthor}} on {{commitDate}}:
              _{{commitMessage}}_